function [latex_code] = beamerGenerator(code, title,figure_name)


jump_line = char(10);

if (strcmp(title,'none') == 0)
    
    latex_code = ['\begin{frame}{' title '}' jump_line ...
        '\begin{figure}[htb]' jump_line ...
        '\centering' jump_line ...
        '\hspace*{-0.0cm}\includegraphics[width=3.3in]{./figs/' figure_name '.eps}' jump_line ...
        '\end{figure}' jump_line ...
        '\end{frame}' jump_line];
else
    latex_code = ['\begin{frame}' jump_line ...
        '\begin{figure}[htb]' jump_line ...
        '\centering' jump_line ...
        '\hspace*{-0.0cm}\includegraphics[width=3.3in]{' figure_name '.eps}' jump_line ...
        '\end{figure}' jump_line ...
        '\end{frame}' jump_line];
end

latex_code = [code jump_line latex_code];

end